/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as RunRouteImport } from './routes/run'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppCodeRouteImport } from './routes/_app.code'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppRepositoryRouteImport } from './routes/_app.repository'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTerminalRouteImport } from './routes/_app.terminal'
import { Route as AppProjectsSlugRouteImport } from './routes/_app.projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoryRoute = AppRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/run': typeof RunRoute
  '/activity': typeof AppActivityRoute
  '/agents': typeof AppAgentsRoute
  '/code': typeof AppCodeRoute
  '/dashboard': typeof AppDashboardRoute
  '/repository': typeof AppRepositoryRoute
  '/settings': typeof AppSettingsRoute
  '/terminal': typeof AppTerminalRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/run': typeof RunRoute
  '/activity': typeof AppActivityRoute
  '/agents': typeof AppAgentsRoute
  '/code': typeof AppCodeRoute
  '/dashboard': typeof AppDashboardRoute
  '/repository': typeof AppRepositoryRoute
  '/settings': typeof AppSettingsRoute
  '/terminal': typeof AppTerminalRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/run': typeof RunRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/code': typeof AppCodeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/repository': typeof AppRepositoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/terminal': typeof AppTerminalRoute
  '/_app/projects/$slug': typeof AppProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/run'
    | '/activity'
    | '/agents'
    | '/code'
    | '/dashboard'
    | '/repository'
    | '/settings'
    | '/terminal'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/run'
    | '/activity'
    | '/agents'
    | '/code'
    | '/dashboard'
    | '/repository'
    | '/settings'
    | '/terminal'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/run'
    | '/_app/activity'
    | '/_app/agents'
    | '/_app/code'
    | '/_app/dashboard'
    | '/_app/repository'
    | '/_app/settings'
    | '/_app/terminal'
    | '/_app/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RunRoute: typeof RunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/code': {
      id: '/_app/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repository': {
      id: '/_app/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AppRepositoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal': {
      id: '/_app/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug': {
      id: '/_app/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppCodeRoute: typeof AppCodeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppRepositoryRoute: typeof AppRepositoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTerminalRoute: typeof AppTerminalRoute
  AppProjectsSlugRoute: typeof AppProjectsSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppCodeRoute: AppCodeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppRepositoryRoute: AppRepositoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTerminalRoute: AppTerminalRoute,
  AppProjectsSlugRoute: AppProjectsSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RunRoute: RunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
